// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           27
// Async Callback:                       1
// Total number of exported functions:  29

#![no_std]
#![feature(alloc_error_handler, lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    price_discovery
    (
        deposit
        withdraw
        redeem
        getCurrentPrice
        getMinLaunchedTokenPrice
        getPricePrecision
        getLaunchedTokenId
        getAcceptedTokenId
        getLaunchedTokenBalance
        getAcceptedTokenBalance
        getStartBlock
        getEndBlock
        setLockingScAddress
        setUnlockEpoch
        getLockingScAddress
        getUnlockEpoch
        getCurrentPhase
        getNoLimitPhaseDurationBlocks
        getLinearPenaltyPhaseDurationBlocks
        getFixedPenaltyPhaseDurationBlocks
        getPenaltyMinPercentage
        getPenaltyMaxPercentage
        getFixedPenaltyPercentage
        issueRedeemToken
        createInitialRedeemTokens
        getRedeemTokenId
        getRedeemTokenTotalCirculatingSupply
        callBack
    )
}
